services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dfajardo
      RABBITMQ_DEFAULT_PASS: df2025
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  web:
    build:
      context: ./sistema_de_mensajeria_web
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=dfajardo
      - RabbitMQ__Password=df2025

volumes:
  rabbitmq_data:

        
  